### ISSUE TITLE
Unhandled exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by vHanda** [SedlarDavid/fire_line_diff#2]
I'm getting this error -

```
Unhandled exception:
Null check operator used on a null value
#0      FireLineDiff._longestCommonSubstring.<anonymous closure> (package:fire_line_diff/fire_line_diff.dart:95:25)
#1      List.forEach (dart:core-patch/growable_array.dart:403:8)
#2      FireLineDiff._longestCommonSubstring (package:fire_line_diff/fire_line_diff.dart:91:21)
#3      FireLineDiff.diff (package:fire_line_diff/fire_line_diff.dart:17:23)
#4      main (package:dart_git/main_diff.dart:16:16)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

here in the smallest code to reproduce it -
```dart
import 'package:fire_line_diff/fire_line_diff.dart';

void main() {
  var a = [
    'class GitException implements Exception {}',
    '',
    'class GitNotFound implements GitException {}',
  ];

  var b = [
    'class GitNotFound implements GitException {}',
    '',
    'class InvalidRepoException implements GitException {'
  ];

  FireLineDiff.diff(a, b);
}
```

**Comment by SedlarDavid** [comment]
@vHanda I will look into that as soon as possible, thank you!

**Comment by vHanda** [comment]
Please take your time. 

I landed up switching to [diff-match-patch](https://github.com/google/diff-match-patch) as I also want a word based diff. This is for my git implementation - [dart-git](https://github.com/GitJournal/dart-git)

**Comment by SedlarDavid** [comment]
New version should be uploaded on pub.dev.
